In [15]:
# reshape()
import numpy as np
arr=np.arange(12)
arr=np.reshape(arr,(3,4)) # 3 ---> row,4---> columns
print(arr)

# example
arr1=np.arange(24)
up_arr1=np.reshape(arr1,(4,6))
print(up_arr1)

# example 3d
arr2=np.arange(20)
arr2=np.reshape(arr2,(2,2,5))
print(arr2)
# arr2.shape
# arr2.ndim
# arr2.dtype
# arr2.size

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


20

In [18]:
# flatten  --> convert Nd array into 1d
import numpy as np
arr=np.arange(12).reshape(3,4)
print(arr)
up_arr=arr.flatten()  # use to convert 2d array in 1d array 
print(up_arr)

# example of 3d
arr1=np.arange(20).reshape(2,2,5)
print(arr1)
up_arr1=arr1.flatten()  # convert 3d array into 1d array 
print(up_arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [26]:
# ravel
import numpy as np
arr2=np.arange(12).reshape(3,4)
up_arr2=arr2.ravel()
print(up_arr2)
print(arr2)
# example 3d
arr3=np.arange(20).reshape(2,2,5)
up_arr3=arr3.ravel()
up_arr3[0]=23
print(up_arr3)
arr3

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[23  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([[[23,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [31]:
# diference between flatten and ravel
# flatten --> create a copy of the array ,does nit  modify the original array
# ravel --> it usually work on real array
arr3=np.arange(20).reshape(2,2,5)
up_arr3=arr3.ravel()
up_arr3[0]=23
print(up_arr3)
arr3

# flatten
arr1=np.arange(20).reshape(2,2,5)
print(arr1)
up_arr1=arr1.flatten()  # convert 3d array into 1d array 
print(up_arr1)
up_arr1[0]=122
print(up_arr1)
print(arr1)

[23  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[122   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [2]:
# transpose  --> rows convert into cols || cols convert into rows
import numpy as np 
arr4=np.arange(12).reshape(3,4)
print(arr4)
up_arr4=arr4.T
up_arr4

# 3d 
arr5=np.arange(20).reshape(2,2,5)
arr5.T


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[[ 0, 10],
        [ 5, 15]],

       [[ 1, 11],
        [ 6, 16]],

       [[ 2, 12],
        [ 7, 17]],

       [[ 3, 13],
        [ 8, 18]],

       [[ 4, 14],
        [ 9, 19]]])

In [29]:
# slicing 
import numpy as np 
arr6=np.arange(11)
arr6
up_arr6=arr6[:3]
up_arr6


# slicing in 2d
arr7=np.arange(16).reshape(8,2)
arr7
up_arr7=arr7[:,-1]
up_arr7

# slicing in 3d
arr8=np.arange(24).reshape(2,2,6)
print(arr8)
print(arr8[0,0,0])
print(arr8[1,1,-1])
# print(arr8[-1])
# print(arr8[:,0:3:1,0:3:1])
print(arr8[[0,1],[0,1],[0,5]])

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]
0
23
[ 0 23]


In [50]:
# loopings
# while loop
# while loop for 1d
import numpy as np 
arr=np.arange(12)
i=0
while i<len(arr):
    print(arr[i],end=" ")
    i+=1
# while loop for 2d
print("\n")
import numpy as np 
arr1=np.arange(12).reshape(3,4)
i=0
while i<len(arr1):
    j=0
    while j<len(arr1[i]):
        print(arr1[i][j],end=" ")
        j+=1
    print()
    i+=1
        
#example 3d 
arr2=np.arange(12).reshape(2,2,3)
i=0
while i<len(arr2):
    print(f"layer {i}")
    j=0
    while j<len(arr2[i]):
        k=0
        while k<len(arr2[i][j]):
            print(arr2[i][j][k],end=" ")
            k+=1
        print()
        j+=1
    i+=1

# print(arr2.shape)

0 1 2 3 4 5 6 7 8 9 10 11 

0 1 2 3 
4 5 6 7 
8 9 10 11 
layer 0
0 1 2 
3 4 5 
layer 1
6 7 8 
9 10 11 


In [64]:
import numpy as np 
# for loop 1d array
arr2=np.arange(12)
for i in range(len(arr2)):
    print(arr2[i],end=" ")
print("\n")
# for loop 2d array
arr3=np.arange(12).reshape(3,4)
for i in range(len(arr3)):
    for j in range(len(arr3[i])):
        print(arr3[i][j],end=" ")
    print()
print("\n")
# for loop 3d array 
arr4=np.arange(12).reshape(2,2,3)
# print(arr4)
for i in range(len(arr4)):
    print(f"layer {i}")
    for j in range(len(arr4[i])):
        for k in range(len(arr4[i][j])):
            print(arr4[i][j][k],end=" ")
        print()
    print()


0 1 2 3 4 5 6 7 8 9 10 11 

0 1 2 3 
4 5 6 7 
8 9 10 11 


layer 0
0 1 2 
3 4 5 

layer 1
6 7 8 
9 10 11 

