In [3]:
# list
import numpy as np
l=[1,2,3]
print(l)

# array 1d
arr=np.array(l)
print(arr)

[1, 2, 3]
[1 2 3]


In [17]:
# 2d list
l=[[1,2,3],[4,5,6]]
print(l)
print(l[0]) # [1,2,3] -->1 row
print(l[0][0])  #  [1,2,3] -->1 row --> 1 --> 1st element

# 2d array
# arr=np.array(l)
# arr=np.array([[1,2,3],[4,5,6]])
arr=np.arange(1,7).reshape(2,3)
print(arr)
print(arr[0]) # [1,2,3] -->1 row
print(arr[0][0])  #  [1,2,3] -->1 row --> 1 --> 1st element
# arr[row][column]
l[1][0]=100
arr[1][0]=100
print(l)
print(arr)

[[1, 2, 3], [4, 5, 6]]
[1, 2, 3]
1
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
[[1, 2, 3], [100, 5, 6]]
[[  1   2   3]
 [100   5   6]]


In [20]:
# list
l=[1,2,3]
lm=l*2
print(lm)
# array
arr=np.array(l)
arrM=arr*2
print(arrM) # multiply each element by 2 which is not in the case of list


[1, 2, 3, 1, 2, 3]
[2 4 6]


In [9]:
# comparison

import time
import numpy as np

# array timing is lesser than list
# array

start=time.time()
arr=np.array(1000)*2
print("array output",time.time() - start)
# list
start=time.time()
l=[i*2 for i in range(1000)]
print("list output",time.time() - start)


array output 0.00011086463928222656
list output 0.00018167495727539062


In [15]:
# zeros array
import numpy as np
arr=np.zeros(6) # 1d 
arr=np.zeros((4,8)) # 2d
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [19]:
# ones array
# 1d
arr=np.ones(7)
print(arr)
# 2d 
arr=np.ones((4,5))
print(arr)

[1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
# ques 
# zeros --> 2d array --> add by 10 
import numpy as np
arr=np.zeros((3,6))
arr=arr+10
print(arr)


array([[10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10.]])

In [27]:
# ques 
# ones --> 2d array --> multiply by 5 
arr1=np.ones((3,5))
arr1=arr1*5
print(arr1)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [31]:
# full for 1d
# .full((range),number)
arr=np.full((3),5)
print(arr)

# full for 2d
arr=np.full((3,5),3)
print(arr)

[5 5 5]
[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [34]:
# question help of zeros --> 2d --> value is 6
arr1=np.zeros((4,5))+6
print(arr)
# question help of full--> 2d --> value is 1
arr2=np.full((2,5),1)
print(arr2)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [36]:
import numpy as np
arr=np.random.random(5)
print(arr)
# random fro 2d array
arr1=np.random.random((2,3))
print(arr1)

[0.39539512 0.77002098 0.78118973 0.86640096 0.20137853]
[[0.69128006 0.81001999 0.38933695]
 [0.63682501 0.42074335 0.17013909]]


In [41]:
# arange for 1d
import numpy as np
arr=np.arange(5)
print(arr)

# arange(start,stop,step)
# # arange for 2d  --> to convert into 2d we need to use reshape
# arr1=np.arange(6).reshape(2,3)
# print(arr1)


[0 1 2 3 4]


In [57]:
# vector(1d) array 
l=[1,2,3,4]
print(l)
# vector 1d array
arr=np.arange(7)
print(arr)
# matrix(2d) list
print("2d")
l1=[[1,2,3],[4,5,6]]
print(l1)
# matrix(2d) array
arr1=np.arange(6).reshape(2,3)
print(arr1)
# tensor(3d) list
print("3d")
l2=[[[1,2,3],[4,5,6]]]
print(l2)
# tensor(3d) array
arr2=np.arange(24).reshape(2,4,3)
print(arr2)

[1, 2, 3, 4]
[0 1 2 3 4 5 6]
2d
[[1, 2, 3], [4, 5, 6]]
[[0 1 2]
 [3 4 5]]
3d
[[[1, 2, 3], [4, 5, 6]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [70]:
# array properity
import numpy as np
arr=np.arange(11)
# print(np.shape(arr))
print(arr.shape)
print("size",np.size(arr))
print("dimension",np.ndim(arr))
print("datatype",arr.dtype)


(11,)
size 11
dimension 1
datatype int64
