In [20]:
# Numpy 
# export --> pickle(package)
import numpy
# import numpy as np
# from numpy import arange
# n=numpy.arange(12)
# print(type(n))
# print(n)
# print(n[0])

# example
# n=numpy.arange(12)
# d=n.reshape(3,4)  # 3 --> row , 4--> column  it is use to convert the array dimension
# print(type(d))
# print(d)

# example
# n=numpy.arange(12).reshape(4,3)
# print(n)

# example  3d
# n=numpy.arange(24).reshape(2,3,4)  # 3--> rows 4--> column
# print(n)


# example split # 2,5,8,11  --> print
# array[row_slice, column_slice]
n=numpy.arange(12).reshape(4,3)
print(n)
print(n[:,2]) # here 2 is specific column
# slicing 
# 2D NumPy Array

# arr = [[ 1,  2,  3,  4],
#        [ 5,  6,  7,  8],
#        [ 9, 10, 11, 12]]

# Indexing:
# Rows    -> 0, 1, 2
# Columns -> 0, 1, 2, 3

# ┌────┬────┬────┬────┐
# │ 1  │ 2  │ 3  │ 4  │  ← row 0
# ├────┼────┼────┼────┤
# │ 5  │ 6  │ 7  │ 8  │  ← row 1
# ├────┼────┼────┼────┤
# │ 9  │10  │11  │12  │  ← row 2
# └────┴────┴────┴────┘

# arr[1]       -> [5 6 7 8]       # 2nd row
# arr[:, 2]    -> [3 7 11]        # 3rd column
# arr[0:2, :]  -> first 2 rows
# arr[:, 1:3]  -> columns 1 and 2
# arr[0:2,1:3] -> [[2 3]
#                   [6 7]]

# Negative Indexing:
# arr[-1]      -> last row
# arr[:, -1]   -> last column

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 2  5  8 11]


In [24]:
# example spilting
import numpy
n=numpy.arange(12).reshape(4,3)
# print(n[1:3,1])
print(n[1:3,1:2])

[[4]
 [7]]
