In [26]:
# sorting 
# sorting for 1d
import numpy as np 
arr=np.array([10,40,30,60,90,7,5])
print(arr)
arr_sort=np.sort(arr)
print(arr_sort)

# sorting for 2d
# axis=1 --> column 
# axis=0 --> rows
arr1=np.array([[5,60,20],[40,90,4]])
print(arr1)
arr1_sort=np.sort(arr1,axis=0)  # by default row wise sort 
print(arr1_sort)

# example for sort 2d
# bt default sorting is asending
arr2=np.array([[3,2,7],[1,5,9]])
print(arr2)
arr2_s=np.sort(arr2)
print(arr2_s)
print("desending sort")
print(np.sort(arr2)[:,::-1])

[10 40 30 60 90  7  5]
[ 5  7 10 30 40 60 90]
[[ 5 60 20]
 [40 90  4]]
[[ 5 60  4]
 [40 90 20]]
[[3 2 7]
 [1 5 9]]
[[2 3 7]
 [1 5 9]]
desending sort
[[7 3 2]
 [9 5 1]]


In [33]:
# filtering
# 1d array 
import numpy as np
arr=np.array([10,20,40,6,3,4,2])
print(arr)
arr_f=arr[arr<40]
print(arr_f)

# example 
arr1=np.array([10,20,30,49,39,11])
print(arr1)
arr1_f=arr1[arr1%2==0]
print(arr1_f)

# factorial
import math
arr2=np.array([2,3,4,5,6,1])
print(arr2)
arr2_f=np.array([math.factorial(x) for x in arr2])
print(arr2_f)

[10 20 40  6  3  4  2]
[10 20  6  3  4  2]
[10 20 30 49 39 11]
[10 20 30]
[2 3 4 5 6 1]
[  2   6  24 120 720   1]


In [45]:
# fancy indexing 
import numpy as np 
arr=np.array([10,20,3,4,90,100])
print(arr)
arr_fancy=arr[[0,2]]
print(arr_fancy)

# 2d array 
arr1=np.array([[90,78,76,12],[20,50,56,89],[14,25,56,87]])
print(arr1)
arr1_f=arr1[[0,2]]
print(arr1_f)

[ 10  20   3   4  90 100]
[10  3]
[[90 78 76 12]
 [20 50 56 89]
 [14 25 56 87]]
[[90 78 76 12]
 [14 25 56 87]]


In [54]:
# where
import numpy as np 
arr=np.array([12,5,6,80,30,40,50])
print(arr)
arr_w=np.where(arr>30,"True","False")  # condition:True:False
print(arr_w) 

# example 
arr1=np.array([12,5,6,80,30,40,50])
print(arr1)
arr1_w=np.where(arr1>30,arr+2,arr-2)  # condition:True:False
print(arr1_w)

# example
age=np.array([10,19,12,15,18,19,17,22,45,65])
print(age)
age_w=np.where(age>18,"Eligible for Vote","Not eligible for vote")
print(age_w)

# example 
exp=np.array([0,1,3,4,5])
print(exp)
exp_w=np.where(exp>2,"senior","junior")
print(exp_w)

[12  5  6 80 30 40 50]
['False' 'False' 'False' 'True' 'False' 'True' 'True']
[12  5  6 80 30 40 50]
[10  3  4 82 28 42 52]
[10 19 12 15 18 19 17 22 45 65]
['Not eligible for vote' 'Eligible for Vote' 'Not eligible for vote'
 'Not eligible for vote' 'Not eligible for vote' 'Eligible for Vote'
 'Not eligible for vote' 'Eligible for Vote' 'Eligible for Vote'
 'Eligible for Vote']
[0 1 3 4 5]
['junior' 'junior' 'senior' 'senior' 'senior']


In [66]:
# concatenation 
import numpy as np 
arr1=np.array([10,20,30])
arr2=np.array([1,2,3])
arr_a=np.concatenate((arr1,arr2))
print(arr_a)
# print("manually",arr1+arr2)
# 2d array 
arr3=np.array(([1,2,3],[4,5,6]))
arr4=np.array(([7,8,9],[10,11,12]))
# arr3_arr4=np.concatenate((arr3,arr4),axis=0) # by default column wise
arr3_arr4=np.concatenate((arr3,arr4),axis=1)
arr3_arr4=np.concatenate((arr3,arr4))
print(arr3_arr4)

[10 20 30  1  2  3]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [73]:
# statistical function 
# **Statistical Functions**
# 1. np.sum(a)
#    -> Sum of all elements
 
# 2. np.mean(a)
#    -> Average = Sum of elements / Number of elements
 
# 3. np.median(a)
#    -> Middle value after sorting
 
# 4. np.min(a)
#    -> Smallest value in array
 
# 5. np.max(a)
#    -> Largest value in array
 
# 6. np.var(a)
#    mean,difference,square,average | (sum = ddof) -> divide by array length
 
# 7. np.std(a)
#    -> Standard Deviation = √Variance
#    -> Measures spread of data
 
# 8. np.prod(a)
#    -> Multiplication of all elements
 
# 9. np.cumsum(a)
#    -> Cumulative (running) sum
 
# 10. np.cumprod(a)
#     -> Cumulative (running) product
 
# 11. np.argmin(a)
#     -> Index position of minimum value
 
# 12. np.argmax(a)
#     -> Index position of maximum value
 
# 13. np.abs(a)
#     -> Converts negative values to positive
#     -> Absolute value (distance from zero)
 
# 14. np.unique(a)
#     -> Returns unique values only
#     -> Removes duplicates
 
# 15. np.percentile(a, 50)
#     -> Finds percentage-based value
#     -> 50th percentile = Median
 
# 16. np.quantile(a, 0.5)
#     -> Similar to percentile
#     -> 0.5 = 50%
 
# 17. np.ptp(a)
#     -> Range = Max - Min
 
# 28. np.any(a)
#     -> True if at least one value is True
 
# np.sum(a) -> Sum of all elements
# np.mean(a) -> Average = Sum of elements / Number of elements
# np.median(a) -> Middle value after sorting
# np.min(a) -> Smallest value in array
# np.max(a) -> Largest value in array
# np.var(a) mean,difference,square,average | (sum = ddof) -> divide by array length
# np.std(a) -> Standard Deviation = √Variance -> Measures spread of data
# np.prod(a) -> Multiplication of all elements
# np.cumsum(a) -> Cumulative (running) sum
# np.cumprod(a) -> Cumulative (running) product
# np.argmin(a) -> Index position of minimum value
# np.argmax(a) -> Index position of maximum value
# np.abs(a) -> Converts negative values to positive -> Absolute value (distance from zero)
# np.unique(a) -> Returns unique values only -> Removes duplicates
# np.percentile(a, 50) -> Finds percentage-based value -> 50th percentile = Median
# np.quantile(a, 0.5) -> Similar to percentile -> 0.5 = 50%
# np.ptp(a) -> Range = Max - Min
# np.any(a) -> True if at least one value is True
 
 
import numpy as np 
statArray=np.array([10,20,30,192,23,1])
print(np.sum(statArray))
print(np.mean(statArray))
print(np.median(statArray))
print(np.min(statArray))
print(np.max(statArray))
print(np.argmin(statArray))
print(np.argmin(statArray))
print(np.prod(statArray))


276
46.0
21.5
1
192
5
5
26496000
